import type { CanonicalTopic } from "./types"

export const canonicalTopics: CanonicalTopic[] = [
  {
    id: "penetration-testing",
    title: "Penetration Testing",
    filePath: "wiki/topics/penetration-testing.md",
    summary: "Core category for authorized penetration testing as a practice, purpose, and assessment type.",
    description: "Penetration testing is the top-level entry point for this wiki. Use it for articles that explain what penetration testing is for, how it differs from adjacent practices, what kinds of questions a pentest answers, and how owners should think about validated security exposure.",
    role: "This is the front door of the eight-category map. Readers should normally begin here, then move into workflow, rules of engagement, environment, and domain-specific branches.",
    includes: [
      "articles about the purpose and scope of penetration testing",
      "comparisons with adjacent practices such as assessment or red teaming",
      "articles on validated exposure, evidence, and reporting value",
      "broad methodology pieces that are not tied to one narrow domain",
    ],
    relatedIds: ["pentest-workflow", "rules-of-engagement", "web-testing"],
    keywords: ["penetration testing", "pentest", "assessment", "validated exposure", "reporting"],
    kind: "topic",
  },
  {
    id: "pentest-workflow",
    title: "Pentest Workflow",
    filePath: "wiki/topics/pentest-workflow.md",
    summary: "Category for the sequence of pentest work from authorization through reporting.",
    description: "Pentest workflow is the operational spine of the wiki. Use it for articles that explain how an engagement moves from permission and preparation into reconnaissance, validation, evidence collection, and reporting.",
    role: "This category follows penetration testing conceptually. It explains how the work is done rather than why the work exists.",
    includes: [
      "workflow models and phase breakdowns",
      "evidence collection and reporting flow",
      "sequencing questions such as what should happen before or after validation",
      "articles that translate pentesting from abstract purpose into ordered work",
    ],
    relatedIds: ["penetration-testing", "rules-of-engagement", "kali-linux"],
    keywords: ["workflow", "phases", "evidence", "reporting", "enumeration", "validation"],
    kind: "topic",
  },
  {
    id: "rules-of-engagement",
    title: "Rules of Engagement",
    filePath: "wiki/topics/rules-of-engagement.md",
    summary: "Category for scope, exclusions, communication paths, risk boundaries, and authorization conditions.",
    description: "Rules of engagement define the boundaries that make authorized testing safe, reviewable, and professionally useful. Use this category for articles about scope, exclusions, communications, incident handling, evidence handling, and operational risk constraints.",
    role: "This is the boundary category of the eight-category map. It sits between abstract methodology and real operational execution.",
    includes: [
      "scope and authorization models",
      "exclusions and prohibited techniques",
      "communications and escalation paths",
      "evidence handling and incident response during testing",
      "boundary-setting articles that keep testing distinguishable from uncontrolled intrusion",
    ],
    relatedIds: ["penetration-testing", "pentest-workflow", "kali-linux"],
    keywords: ["scope", "authorization", "communications", "exclusions", "incident handling", "boundaries"],
    kind: "topic",
  },
  {
    id: "kali-linux",
    title: "Kali Linux",
    filePath: "wiki/topics/kali-linux.md",
    summary: "Main category for Kali Linux as the primary assessment-environment subject in the current wiki.",
    description: "Kali Linux is the main environment-focused category in this wiki. Use it for articles that explain what Kali Linux is, why it matters in authorized testing and labs, how it is packaged, and how it should be understood within the broader assessment workflow.",
    role: "This is the main environment category. It branches into a practical learner view and a conceptual environment-versus-methodology view.",
    includes: [
      "overview articles on Kali Linux as a platform",
      "image, packaging, distribution, and release-model topics",
      "broad environment-selection questions",
      "articles that treat Kali Linux as a major subject rather than a narrow operational tip",
    ],
    relatedIds: ["practical-kali-linux", "kali-as-an-assessment-environment", "pentest-workflow"],
    keywords: ["kali", "distribution", "images", "metapackages", "nethunter", "platform"],
    kind: "topic",
  },
  {
    id: "practical-kali-linux",
    title: "Practical Kali Linux",
    filePath: "wiki/topics/practical-kali-linux.md",
    summary: "Applied learner-facing category for using Kali Linux in labs, practice, and repeatable assessment setups.",
    description: "Practical Kali Linux is the applied branch of the Kali cluster. Use it for articles that help a learner or practitioner make concrete environment decisions without turning the environment itself into the main intellectual subject.",
    role: "This category narrows Kali Linux into real usage decisions. It is more applied than the main Kali page and less conceptual than the assessment-environment page.",
    includes: [
      "choosing images and installation styles for labs",
      "metapackage and tool-scope decisions",
      "repeatable learner setups",
      "common operational mistakes in lab use",
      "practical environment discipline for notes, rollback, and evidence handling",
    ],
    relatedIds: ["kali-linux", "kali-as-an-assessment-environment", "rules-of-engagement"],
    keywords: ["vm", "lab", "practice", "installer image", "live image", "tooling"],
    kind: "topic",
  },
  {
    id: "kali-as-an-assessment-environment",
    title: "Kali as an Assessment Environment",
    filePath: "wiki/topics/kali-as-an-assessment-environment.md",
    summary: "Conceptual category for treating Kali Linux as an environment rather than a testing methodology.",
    description: "This category exists to enforce an important distinction: Kali Linux is an assessment environment, not a methodology. Use it for articles that explain why that distinction matters and how environment design supports, but does not define, authorized security work.",
    role: "This is the conceptual branch of the Kali cluster. It keeps the wiki from collapsing environment choice into security methodology.",
    includes: [
      "environment-versus-methodology articles",
      "portability and repeatability as environment traits",
      "operator-readiness discussions",
      "articles that generalize from Kali to broader environment thinking",
    ],
    relatedIds: ["kali-linux", "practical-kali-linux", "pentest-workflow"],
    keywords: ["environment", "repeatability", "portability", "methodology", "operator readiness"],
    kind: "topic",
  },
  {
    id: "web-testing",
    title: "Web Testing",
    filePath: "wiki/topics/web-testing.md",
    summary: "Domain-specific category for web application and API testing within the larger pentest model.",
    description: "Web testing is the main domain-specific branch in the current wiki. Use it for articles about how penetration-testing logic applies to web applications, APIs, identity flows, sessions, input handling, and application behavior.",
    role: "This category is where the main pentesting flow becomes domain-specific. It should connect strongly to the OWASP WSTG framework anchor.",
    includes: [
      "web application and API testing topics",
      "authentication, authorization, session, and application-logic assessment",
      "domain-specific methodology pieces for web targets",
      "articles that connect pentest workflow to web behavior and trust boundaries",
    ],
    relatedIds: ["penetration-testing", "pentest-workflow", "owasp-wstg"],
    keywords: ["web", "application", "api", "authentication", "session", "authorization", "http"],
    kind: "topic",
  },
  {
    id: "owasp-wstg",
    title: "OWASP WSTG",
    filePath: "wiki/frameworks/owasp-wstg.md",
    summary: "Framework-anchor category for articles that use the OWASP Web Security Testing Guide to structure web-testing work.",
    description: "OWASP WSTG is the framework anchor for the web-testing side of the wiki. Use it for articles that explain, extend, compare, or apply the OWASP Web Security Testing Guide as a structured approach to web application testing.",
    role: "This is the one framework category in the eight-category backbone. It supports the web-testing branch without replacing the broader pentest model.",
    includes: [
      "articles about how WSTG organizes web testing",
      "framework comparisons and mappings",
      "articles that explain how to use WSTG in practice",
      "methodology pieces that are clearly rooted in the framework",
    ],
    relatedIds: ["web-testing", "pentest-workflow", "penetration-testing"],
    keywords: ["owasp", "wstg", "framework", "web security testing guide", "test cases"],
    kind: "framework",
  },
]

export function getCanonicalTopic(id: string): CanonicalTopic | undefined {
  return canonicalTopics.find((topic) => topic.id === id)
}
