import type { CanonicalTopic } from "./types"

export const canonicalTopics: CanonicalTopic[] = [
  {
    id: "recon",
    title: "Recon",
    filePath: "wiki/topics/recon.md",
    summary: "Discovery, mapping, enumeration, and target understanding before deeper validation or exploitation.",
    description: "Recon is the discovery and orientation layer of the wiki. Use it for material that helps the reader understand what exists, how a target is exposed, where boundaries sit, and what deserves deeper scrutiny before intrusive validation starts.",
    role: "Start here when the problem is target understanding rather than payload delivery. Recon should turn an unknown environment into a legible one.",
    includes: [
      "asset discovery, enumeration, and attack-surface mapping",
      "service and application discovery",
      "internet-facing exposure analysis",
      "environment and lab decisions that directly support early assessment work",
    ],
    relatedIds: ["web", "creds", "pivot"],
    keywords: ["recon", "enumeration", "attack surface", "osint", "subdomains", "service discovery"],
    companionSummary: "The companion corpus contributes asset-discovery, internet-mapping, and early target-enumeration articles that fit naturally under Recon.",
    companionArticles: [
      { fileName: "nmap.md", title: "Nmap" },
      { fileName: "amass.md", title: "OWASP Amass" },
      { fileName: "subfinder.md", title: "Subfinder" },
      { fileName: "theharvester.md", title: "theHarvester" },
      { fileName: "dnsrecon.md", title: "DNSRecon" },
      { fileName: "gobuster.md", title: "Gobuster" },
      { fileName: "shodan.md", title: "Shodan" },
      { fileName: "urlscan-io.md", title: "urlscan.io" },
      { fileName: "whois.md", title: "WHOIS" },
      { fileName: "crt-sh.md", title: "crt.sh" },
      { fileName: "wayback-machine.md", title: "Wayback Machine" },
    ],
    kind: "topic",
  },
  {
    id: "web",
    title: "Web",
    filePath: "wiki/topics/web.md",
    summary: "Web application and API testing, with emphasis on application behavior, trust boundaries, and request handling.",
    description: "Web is the application-testing branch of the wiki. It covers how browser-facing and API-facing systems are examined, how requests and responses are interpreted, and how application logic turns into security findings.",
    role: "Use Web when the main object of study is a web application, API, identity flow, session model, or browser-mediated trust boundary.",
    includes: [
      "intercepting proxies and traffic inspection",
      "parameter discovery and request shaping",
      "authentication, session, and authorization testing",
      "frameworks and tooling for application-layer assessment",
    ],
    relatedIds: ["recon", "exploit", "creds"],
    keywords: ["web", "api", "proxy", "http", "burp", "zaproxy", "wstg"],
    companionSummary: "The companion corpus is richest here. It contains practical articles on proxies, request tooling, fuzzers, and web-focused scanners that can deepen this category quickly.",
    companionArticles: [
      { fileName: "burp-suite.md", title: "Burp Suite" },
      { fileName: "zaproxy.md", title: "OWASP ZAP" },
      { fileName: "postman.md", title: "Postman" },
      { fileName: "altair-graphql-client.md", title: "Altair GraphQL Client" },
      { fileName: "swagger-ui-detector.md", title: "Swagger UI Detector" },
      { fileName: "arjun.md", title: "Arjun" },
      { fileName: "nikto.md", title: "Nikto" },
      { fileName: "ffuf.md", title: "ffuf" },
      { fileName: "wfuzz.md", title: "Wfuzz" },
      { fileName: "xsstrike.md", title: "XSStrike" },
      { fileName: "sqlmap.md", title: "sqlmap" },
    ],
    kind: "topic",
  },
  {
    id: "exploit",
    title: "Exploit",
    filePath: "wiki/topics/exploit.md",
    summary: "Controlled validation of weaknesses through payloads, exploit frameworks, and exploit-adjacent tooling.",
    description: "Exploit is where verified weaknesses turn into controlled proof, access, or impact. It should hold articles that explain exploit frameworks, exploit helpers, payload-delivery tooling, and the difference between finding a weakness and safely validating it.",
    role: "Use Exploit when the center of gravity is proof and controlled execution rather than discovery alone. It normally follows Recon and often works alongside Web or Creds.",
    includes: [
      "exploit frameworks and template-driven validation tools",
      "payload-generation and exploit-delivery tooling",
      "controlled proof of exploitability",
      "articles that connect technical weaknesses to demonstrable impact",
    ],
    relatedIds: ["web", "creds", "post"],
    keywords: ["exploit", "payload", "template", "rce", "framework", "validation"],
    companionSummary: "The companion corpus provides concrete exploit-adjacent tool pages here, especially around templated validation, payload tooling, and exploit automation.",
    companionArticles: [
      { fileName: "nuclei.md", title: "Nuclei" },
      { fileName: "metasploit-framework.md", title: "Metasploit Framework" },
      { fileName: "sqlmap.md", title: "sqlmap" },
      { fileName: "commix.md", title: "Commix" },
      { fileName: "tplmap.md", title: "Tplmap" },
      { fileName: "xxeinjector.md", title: "XXEinjector" },
      { fileName: "ysoserial.md", title: "ysoserial" },
      { fileName: "ysoserial-net.md", title: "ysoserial.net" },
      { fileName: "subjack.md", title: "Subjack" },
      { fileName: "wafw00f.md", title: "WAFW00F" },
      { fileName: "aircrack-ng-suite.md", title: "Aircrack-ng Suite" },
    ],
    kind: "topic",
  },
  {
    id: "creds",
    title: "Creds",
    filePath: "wiki/topics/creds.md",
    summary: "Credential capture, relay, cracking, token handling, and identity material as an operational category.",
    description: "Creds organizes the identity and authentication side of offensive work. It is where hashes, tickets, challenge-response flows, password attacks, relay paths, and reusable credential material belong.",
    role: "Use Creds when the key question is how identity material is discovered, replayed, relayed, cracked, or reused across an assessment.",
    includes: [
      "hashes, passwords, tickets, and authentication artifacts",
      "capture and relay tooling",
      "password and hash cracking workflows",
      "articles about identity as an attack surface",
    ],
    relatedIds: ["recon", "exploit", "post", "pivot"],
    keywords: ["credentials", "hashes", "relay", "kerberos", "ntlm", "passwords"],
    companionSummary: "The companion corpus gives this category practical anchors around credential capture, cracking, NTLM relay, and identity-centric tooling.",
    companionArticles: [
      { fileName: "responder.md", title: "Responder" },
      { fileName: "ntlmrelayx.md", title: "ntlmrelayx" },
      { fileName: "hashcat.md", title: "Hashcat" },
      { fileName: "hydra.md", title: "Hydra" },
      { fileName: "john-the-ripper.md", title: "John the Ripper" },
      { fileName: "mimikatz.md", title: "Mimikatz" },
      { fileName: "impacket.md", title: "Impacket" },
      { fileName: "crackmapexec.md", title: "CrackMapExec" },
      { fileName: "enum4linux-ng.md", title: "enum4linux-ng" },
    ],
    kind: "topic",
  },
  {
    id: "post",
    title: "Post",
    filePath: "wiki/topics/post.md",
    summary: "Post-exploitation, local context gathering, privilege escalation analysis, and evidence-rich follow-on work after initial access.",
    description: "Post is where the wiki covers what happens after access is established. It includes host and identity context gathering, local privilege work, persistence evaluation, evidence capture, and the analysis needed to explain what access really means.",
    role: "Use Post when an article is about working from a foothold rather than reaching one. It should connect strongly to Creds and Pivot.",
    includes: [
      "host and directory-context analysis after access",
      "privilege escalation and local situational awareness",
      "evidence capture from compromised hosts",
      "articles about turning initial access into defensible understanding",
    ],
    relatedIds: ["creds", "pivot", "exploit"],
    keywords: ["post", "host context", "privilege escalation", "bloodhound", "peas", "volatility"],
    companionSummary: "The companion corpus gives Post its first serious body of material, especially around host context, Active Directory analysis, and local-enumeration helpers.",
    companionArticles: [
      { fileName: "bloodhound.md", title: "BloodHound" },
      { fileName: "crackmapexec.md", title: "CrackMapExec" },
      { fileName: "wmiexec.md", title: "wmiexec" },
      { fileName: "winpeas.md", title: "winPEAS" },
      { fileName: "linpeas.md", title: "linPEAS" },
      { fileName: "mimikatz.md", title: "Mimikatz" },
      { fileName: "sysinternals-autoruns.md", title: "Sysinternals Autoruns" },
      { fileName: "volatility.md", title: "Volatility" },
      { fileName: "wireshark.md", title: "Wireshark" },
      { fileName: "tcpdump.md", title: "tcpdump" },
    ],
    kind: "topic",
  },
  {
    id: "pivot",
    title: "Pivot",
    filePath: "wiki/topics/pivot.md",
    summary: "Movement across network, host, and trust boundaries through relays, tunnels, proxies, and remote-execution paths.",
    description: "Pivot covers how access moves. It includes articles on relaying, tunneling, remote execution, lateral movement paths, segmented-network traversal, and the practical infrastructure that carries an assessment from one boundary to the next.",
    role: "Use Pivot when the primary question is not whether access exists, but how that access can be extended, relayed, or carried across boundaries safely and intelligibly.",
    includes: [
      "remote execution and lateral movement tooling",
      "relay and tunnel patterns",
      "segmentation traversal and access extension",
      "articles about movement paths between systems or network segments",
    ],
    relatedIds: ["recon", "creds", "post"],
    keywords: ["pivot", "lateral movement", "relay", "tunnel", "remote exec", "segmentation"],
    companionSummary: "Pivot is thinner than the other companion-backed categories, but the companion corpus still gives it enough material to define remote execution, relay, and movement patterns coherently.",
    companionArticles: [
      { fileName: "ntlmrelayx.md", title: "ntlmrelayx" },
      { fileName: "wmiexec.md", title: "wmiexec" },
      { fileName: "smbclient.md", title: "smbclient" },
      { fileName: "wireguard.md", title: "WireGuard" },
      { fileName: "ssrfmap.md", title: "SSRFmap" },
      { fileName: "winrm.md", title: "WinRM" },
      { fileName: "impacket.md", title: "Impacket" },
      { fileName: "bettercap.md", title: "Bettercap" },
    ],
    kind: "topic",
  },
]

export function getCanonicalTopic(id: string): CanonicalTopic | undefined {
  return canonicalTopics.find((topic) => topic.id === id)
}
